### ISSUE TITLE
Erroneous validation error

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#423]
@kittaakos , one of our applications has an error that seems erroneous. Attached is a project with a very reduced instance of the problem and another case which seems to me to be very similar which does not have the error.
The error occurs in ScnBusBindings.sadl. The subjects of both statements are found in the first imported model. I believe that this should be a valid statement.
The similar case is test2.sadl, which has a prefixed subject in the imported file but no validation error occurs. Could you take a quick look at this and see if you can understand why this error is occurring and how to fix it? The file with the error is generated programmatically and the prefixes are considered necessary as there might be the same localname for the SadlResource in another import.

[TestProject.zip](https://github.com/crapo/sadlos2/files/4564016/TestProject.zip)

**Comment by crapo** [comment]
@kittaakos , as far as I know this issue is the only thing preventing me from releasing SADL 3.3.0 on github, for which we have some people waiting. If you could take a look I would appreciate it.

**Comment by kittaakos** [comment]
I was still busy with the version updates, web-sadl does not work currently: https://github.com/crapo/sadlos2/issues/428

**Comment by kittaakos** [comment]
Fortunately, it is not a scooping issue. The validation error is caused by our custom logic from the SADL validator. The commit is [here](https://github.com/crapo/sadlos2/commit/424ac0d969bea4ca67335a0a52d8588213a799ae), do you remember why you have added it?

If I comment out the following part in the SADL validator and run all the core and UI tests, all of them pass. And the problem is also resolved in the test project you have attached to this issue:
```java
if (nm.contains(':')) {
  error("Invalid declaration of new concept with a QName from another namespace", SADL_RESOURCE__NAME)
}
```

I am happy to help to resolve the issue if you can specify the validation constraint. Or we just remove it if there isn't a good reason for keeping it.

**Comment by crapo** [comment]
@kittaakos , I think it isn't quite that simple. True that commenting out the code in SADLValidator makes the error go away, but the concept is still not linked to the correct location. The subject of the statement "scn:c1DeliveryDroneSystem.ImplDeliveryDroneSystem has base:binding ethernet." should be hyperlinked to the declaration of "c1DeliveryDroneSystem.ImplDeliveryDroneSystem" in the import ScnConnections.sadl, prefix "scn", which it is if I remove the prefix in the statement in the importing model. The comparison with the slightly simpler test files is that they have correct linking and this one does not. The offending validation can probably be narrowed to be a truly invalid declaration statement, as opposed to adding additional information, and I can take care of that once the linking is resolved.

**Comment by kittaakos** [comment]
> but the concept is still not linked to the correct location.

I see what you mean. Then I was wrong, and this is a scooping issue 😊 I am looking into it. Thank you for the clarification.

**Comment by crapo** [comment]
More detail: in JenaBasedSadlModelProcessor, line  9720, this line: 
		`	instUri = getDeclarationExtensions().getConceptUri(sr);`
returns 
`http://sadl.org/STEM/Scenario3#scn:c1DeliveryDroneSystem.ImplDeliveryDroneSystem`
so it has the right namespace for the imported concept but not the right local fragment (concrete name) as it put the prefix into the local fragment.

**Comment by kittaakos** [comment]
> but the concept is still not linked to the correct location.

I have fixed the scoping/linking issue and added your example as a test. PR: https://github.com/crapo/sadlos2/pull/431

I did not do anything with the validation.
